defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  host: localhost
  username: <%= Rails.application.secrets.database_username %>

development:
  <<: *defaults
  database: device-management-development

test:
  <<: *defaults
  database: device-management-test

production:
  adapter: postgresql
  database: device-management-production
  host: <%= Rails.application.secrets.database_host %>
  username: <%= Rails.application.secrets.database_username %>
  password: <%= Rails.application.secrets.database_password %>
