# Be sure to restart your server when you modify this file.
common: &common
  database_username: <%= ENV["DATABASE_USERNAME"] %>
  database_password: <%= ENV["DATABASE_USERNAME"] %>
  database_host: <%= ENV["DATABASE_HOST"] %>

sentry: &sentry

router: &router
  router_port: <%= ENV["ROUTER_PORT"] %>
  router_host: <%= ENV["ROUTER_HOST"] %>
  router_username: <%= ENV["ROUTER_USERNAME"] %>
  router_password: <%= ENV["ROUTER_PASSWORD"] %>

nexudus: &nexudus
  nexudus_username: <%= ENV["NEXUDUS_USERNAME"] %>
  nexudus_password: <%= ENV["NEXUDUS_PASSWORD"] %>

development:
  <<: *common
  <<: *router
  <<: *nexudus
  devise_pepper: secret-devise-pepper
  devise_secret: secret-devise-key
  secret_key_base: super-secret-key

test:
  <<: *common
  <<: *nexudus
  <<: *router
  devise_pepper: secret-devise-pepper
  devise_secret: secret-devise-key
  secret_key_base: super-secret-key

staging:
  <<: *common
  <<: *nexudus
  <<: *router
  <<: *sentry
  devise_pepper: <%= ENV["DEVISE_PEPPER"] %>
  devise_secret: <%= ENV["DEVISE_SECRET"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

production:
  <<: *common
  <<: *nexudus
  <<: *router
  <<: *sentry
  devise_pepper: <%= ENV["DEVISE_PEPPER"] %>
  devise_secret: <%= ENV["DEVISE_SECRET"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
